function [dX_dt] = system_eqns_with_ca_signal_v2(t,X,Ca_forcing)
%SYSTEM_EQNS creates system of differential equations for the
%            astrocyte ion concentration tracking model
%            with a prescribed ca FORCING TERM
%       dX/dt = F(X)
% where X = (Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, H_out, Vm) 
%tracks changes in intra- and extra-cellular ion concentrations
%of extracellular ions:
%       Glu, K+, Ca2+, Na+ (Glu_out, K_out, Ca_out, Na_out)
%and intracellular ions:
%       K+, Ca2+, Na+ (K_in, Ca_in, Na_in)
%through EAAT2, Kir4.1, NCX, and NKA
%also keeps track of astrocyte membrane potential Vm

global F g_EAAT2 g_Kir41 g_NCX rho_NKA VolE VolA ...
    g_leak g_Na_leak1 g_Na_leak2 g_K_leak g_Ca_leak

%other parameters
C = 15e-12; %15pF from Sibille et al 2015
C = C*1e3; %astrocyte capacitance times 1e3 for unit conversion from V/C to mV/C
Vleak = -80; %resting membrane potential roughly -80mV, Kirischuk et al. 2012
H_out = (10^(-7.4))*1e3; %mM - Kirischuk et al. 2012
K_in_rest = 140; %mM
Na_in_rest = 16.6; %mM
Ca_in_rest = 73*1e-6; %mM - Kirischuk et al. 2012

%differential equations for the system

dVm_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm) ...
        -(1/C).*(rho_NKA.*nka_current(Na_in,K_out) ...
        + g_NCX.*ncx_current(Na_out,Na_in,Ca_out,Ca_in,Vm)...
        + g_Kir41.*kir41_current(K_out,K_in,Vm)...
        + g_EAAT2.*eaat2_current(Na_out,Glu_out, H_out, K_in,K_out,Vm)...
        + g_leak.*(Vm - Vleak) ...
        + g_Na_leak1.*na_leak_current(Na_out,Na_in,Vm))...
        +g_Na_leak2.*F.*VolA.*(Na_in - Na_in_rest) ...
        +g_K_leak.*F.*VolA.*(K_in - K_in_rest) ...
        +g_Ca_leak.*F.*VolA.*(Ca_in - Ca_in_rest);
    
dNa_in_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm) ...
    (1/(VolA*F)).*(-3.*g_NCX.*ncx_current(Na_out,Na_in,Ca_out,Ca_in,Vm)...
            -3.*rho_NKA.*nka_current(Na_in,K_out) ...
            -3/2.*g_EAAT2.*eaat2_current(Na_out,Glu_out, H_out, K_in,K_out,Vm)...
            -g_Na_leak1.*na_leak_current(Na_out,Na_in,Vm))...
            -g_Na_leak2.*(Na_in - Na_in_rest);
        
dNa_out_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm) ...
    (1/(VolE*F)).*(+3.*g_NCX.*ncx_current(Na_out,Na_in,Ca_out,Ca_in,Vm)...
            +3.*rho_NKA.*nka_current(Na_in,K_out) ...
            +3/2.*g_EAAT2.*eaat2_current(Na_out,Glu_out, H_out, K_in,K_out,Vm)...
            +g_Na_leak1.*na_leak_current(Na_out,Na_in,Vm));
     %-(VolA/VolE).*dNa_in_dt(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm);
        

dK_in_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm) ...
    (1/(VolA*F)).*(-1.*g_Kir41.*kir41_current(K_out,K_in,Vm)...
            +1.*rho_NKA.*nka_current(Na_in,K_out) ...
            +1/2.*g_EAAT2.*eaat2_current(Na_out,Glu_out, H_out, K_in,K_out,Vm))...
            -g_K_leak.*(K_in - K_in_rest);

dK_out_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm) ...
...%     -(VolA/VolE).*dK_in_dt(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm);
 (1/(VolE*F)).*(+1.*g_Kir41.*kir41_current(K_out,K_in,Vm)...
            -1.*rho_NKA.*nka_current(Na_in,K_out) ...
            -1/2.*g_EAAT2.*eaat2_current(Na_out,Glu_out, H_out, K_in,K_out,Vm));


dCa_in_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm, Ca_forcing) ...
    (1/(VolA*F)).*(1.*g_NCX.*ncx_current(Na_out,Na_in,Ca_out,Ca_in,Vm))...
    +Ca_forcing ...
    -g_Ca_leak.*(Ca_in - Ca_in_rest); %leak back into ER

dCa_out_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out,  Vm) ...
    (1/(VolE*F)).*(-1.*g_NCX.*ncx_current(Na_out,Na_in,Ca_out,Ca_in,Vm));
%     -(VolA/VolE).*dCa_in_dt(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm);
    

dGlu_out_dt = @(Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out, Vm) ...
    (1/(VolE*F)).*(1/2.*g_EAAT2.*eaat2_current(Na_out,Glu_out, H_out, K_in,K_out,Vm));

%system form
%X = (Na_in, K_in, Ca_in, Na_out, K_out, Ca_out, Glu_out,Vm)
dX_dt = ...
    [dNa_in_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8)); ...
    dK_in_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8)); ...
    dCa_in_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8), Ca_forcing(t)); ...
    dNa_out_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8)); ...
    dK_out_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8)); ...
    dCa_out_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8)); ...
    dGlu_out_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8)); ...
    dVm_dt(X(1), X(2), X(3), X(4), X(5), X(6), X(7), X(8));];



end


